# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd43f7ffa50962b64abb4dfbf53eb061218c9892d2626b0f4bd40b5119c3fd8407b74406183b6bd916915903dd9e6257db50d5dca6e165873a8e9133b01efd27

test:
  secret_key_base: dd7ca166b5757049e80c6bce45b20f03c398680e9e5a9080e2d925a20da873a2d273484f9f5b2d8345e78e22bfe1316f363f1c6748b759a0158251a58c557385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
